# Generated by Django 2.2.3 on 2019-07-28 10:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=16)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=100)),
                ('group_description', models.CharField(max_length=140)),
                ('group_admin', models.EmailField(max_length=254)),
                ('maximum_capacity', models.IntegerField()),
                ('contribution_amount', models.IntegerField()),
                ('searchable', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='GroupPayoutLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('payout_amount', models.IntegerField()),
                ('payout_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.AccountGroup')),
            ],
        ),
        migrations.CreateModel(
            name='GroupPayoutList',
            fields=[
                ('gpl_id', models.AutoField(primary_key=True, serialize=False)),
                ('payout_status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.AccountGroup')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='GroupContribution',
            fields=[
                ('gc_id', models.AutoField(primary_key=True, serialize=False)),
                ('contribution_amount', models.IntegerField()),
                ('contribution_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.AccountGroup')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='group_id',
            field=models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.AccountGroup'),
        ),
    ]
