# Generated by Django 2.2.3 on 2019-07-28 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='group_id',
            field=models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AccountGroup'),
        ),
    ]
