# Generated by Django 2.2.3 on 2019-07-30 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190728_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountGroupRelationship',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(blank=True, default=False, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
                ('group_id', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='api.AccountGroup')),
            ],
        ),
    ]
