# Generated by Django 2.2.3 on 2019-08-01 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_accountgrouprelationship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='group_id',
        ),
    ]
