# Generated by Django 2.2.3 on 2019-08-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_accountgroup_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='group_code',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
