# Generated by Django 2.2.3 on 2019-08-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190801_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='group_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
